---
name: "Bump CIVO marketplace Argocd version"
pipelineid: argocd

sources:
  # Monitor the version in the Chart.yaml file from the argocd git repository referenced by scmid
  chart:
    kind: yaml
    name: Get latest Argocd Helm Chart version
    scmid: argo-helm
    spec:
      file: charts/argo-cd/Chart.yaml
      key: version

  # Monitor the appVersion in the Chart.yaml file from the argocd git repository referenced by scmid
  appVersion:
    kind: yaml
    name: Get latest Argocd Helm Chart version
    scmid: argo-helm
    spec:
      file: charts/argo-cd/Chart.yaml
      key: appVersion

  app:
    # Using the githubrelease allows us to retrieve the changelog information
    # It will fails if the version mentionned by appVersion do not have an equivalent published
    # GitHub release
    kind: githubrelease
    name: Get latest Argocd version
    dependson:
      - appVersion
    spec:
      owner: argoproj 
      repository: argo-cd
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      versionfilter:
        kind: semver
        pattern: '{{ source "appVersion" }}'

conditions:
  chart:
    # Ensure that the Helm chart version specified on the git repository
    # is correctly published on the argoproj helm repository
    kind: helmchart
    name: Get latest Argocd Helm Chart version
    sourceid: chart
    spec:
      url: https://argoproj.github.io/argo-helm
      name: argo-cd

targets:
  manifest:
    kind: yaml
    name: Update argocd/manifest.yaml
    scmid: kubernetes-marketplace
    spec:
      file: argocd/manifest.yaml
      key: version
    sourceid: app

  install:
    kind: file
    name: Update argocd/install.sh
    scmid: kubernetes-marketplace
    disablesourceinput: true
    spec:
      file: argocd/install.sh
      matchpattern: '--version (v{0,1})(\d*.\d*.\d*)'
      replacepattern: '--version {{ source "chart" }}'

# Define git repository configuration to know where to push changes
# Values are templated and provided via the values.yaml so we can easily 
# adapt to the repository owner.
scms:
  kubernetes-marketplace:
    kind: "github"
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      branch: "{{ .github.branch }}"
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'

  argo-helm:
    kind: "github"
    spec:
      owner: argoproj
      repository: argo-helm
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      branch: main

actions:  
  kubernetes-marketplace:
    kind: "github/pullrequest"
    scmid: kubernetes-marketplace
    title: 'Bump Argocd Helm chart to {{ source "chart" }}'
    spec:
      description: For full list of changes please check ArtifactHub [changelog](https://artifacthub.io/packages/helm/argo/argo-cd?modal=changelog)
      usetitleforautomerge: true
      mergemethod: squash
      labels:
        - enhancement 
